# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui',
# licensing of 'window.ui' applies.
#
# Created: Wed Dec 11 21:52:18 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from basic import zk


class Ui_Tabulky(object):
    def setupUi(self, Tabulky):
        Tabulky.setObjectName("Tabulky")
        Tabulky.setWindowModality(QtCore.Qt.WindowModal)
        Tabulky.resize(978, 793)
        Tabulky.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Obrázky/Snímek z 2019-12-11 13-38-31.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Tabulky.setWindowIcon(icon)
        Tabulky.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Tabulky)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 981, 791))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 979, 789))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 981, 811))
        self.tabWidget.setObjectName("tabWidget")
        #region Basic
        self.basic = QtWidgets.QWidget()
        self.basic.setObjectName("basic")
        self.Password_2 = QtWidgets.QLineEdit(self.basic)
        self.Password_2.setGeometry(QtCore.QRect(300, 30, 151, 21))
        self.Password_2.setObjectName("Password_2")
        self.label_32 = QtWidgets.QLabel(self.basic)
        self.label_32.setGeometry(QtCore.QRect(740, 30, 67, 17))
        self.label_32.setObjectName("label_32")
        self.LogIn_2 = QtWidgets.QLineEdit(self.basic)
        self.LogIn_2.setGeometry(QtCore.QRect(80, 30, 151, 21))
        self.LogIn_2.setObjectName("LogIn_2")
        self.line_12 = QtWidgets.QFrame(self.basic)
        self.line_12.setGeometry(QtCore.QRect(70, 10, 891, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.driver_path_2 = QtWidgets.QLineEdit(self.basic)
        self.driver_path_2.setGeometry(QtCore.QRect(580, 30, 151, 21))
        self.driver_path_2.setObjectName("driver_path_2")
        self.number_land = QtWidgets.QComboBox(self.basic)
        self.number_land.setGeometry(QtCore.QRect(790, 30, 161, 21))
        self.number_land.setObjectName("number_land")
        self.number_land.addItem("")
        self.number_land.addItem("")
        self.number_land.addItem("")
        self.number_land.addItem("")
        self.password_2 = QtWidgets.QLabel(self.basic)
        self.password_2.setGeometry(QtCore.QRect(250, 20, 41, 41))
        self.password_2.setObjectName("password_2")
        self.login_2 = QtWidgets.QLabel(self.basic)
        self.login_2.setGeometry(QtCore.QRect(30, 20, 41, 41))
        self.login_2.setObjectName("login_2")
        self.label_20 = QtWidgets.QLabel(self.basic)
        self.label_20.setGeometry(QtCore.QRect(30, 110, 67, 17))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.basic)
        self.label_21.setGeometry(QtCore.QRect(10, 6, 67, 21))
        self.label_21.setObjectName("label_21")
        self.label_31 = QtWidgets.QLabel(self.basic)
        self.label_31.setGeometry(QtCore.QRect(470, 30, 111, 21))
        self.label_31.setObjectName("label_31")
        self.label_13 = QtWidgets.QLabel(self.basic)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 67, 17))
        self.label_13.setObjectName("label_13")
        self.line_11 = QtWidgets.QFrame(self.basic)
        self.line_11.setGeometry(QtCore.QRect(40, 95, 931, 31))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.textEdit = QtWidgets.QTextEdit(self.basic)
        self.textEdit.setGeometry(QtCore.QRect(40, 120, 921, 631))
        self.textEdit.setObjectName("textEdit")
        self.create_save = QtWidgets.QPushButton(self.basic)
        self.create_save.setGeometry(QtCore.QRect(330, 70, 301, 25))
        self.create_save.setObjectName("create_save")
        self.create_save.clicked.connect(self.changetext)  # Button save nastavení
        self.tabWidget.addTab(self.basic, "")
        # endregion
        self.trh = QtWidgets.QWidget()
        self.trh.setObjectName("trh")
        self.trh_whathap = QtWidgets.QTextEdit(self.trh)
        self.trh_whathap.setGeometry(QtCore.QRect(30, 510, 931, 241))
        self.trh_whathap.setObjectName("trh_whathap")
        self.label_35 = QtWidgets.QLabel(self.trh)
        self.label_35.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.label_35.setObjectName("label_35")
        self.line_15 = QtWidgets.QFrame(self.trh)
        self.line_15.setGeometry(QtCore.QRect(110, 481, 861, 31))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.label_10 = QtWidgets.QLabel(self.trh)
        self.label_10.setGeometry(QtCore.QRect(10, 7, 151, 17))
        self.label_10.setObjectName("label_10")
        self.line_6 = QtWidgets.QFrame(self.trh)
        self.line_6.setGeometry(QtCore.QRect(160, 0, 811, 31))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_14 = QtWidgets.QLabel(self.trh)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 241, 17))
        self.label_14.setObjectName("label_14")
        self.trhinf_button_tabulka = QtWidgets.QPushButton(self.trh)
        self.trhinf_button_tabulka.setGeometry(QtCore.QRect(50, 64, 231, 31))
        self.trhinf_button_tabulka.setObjectName("trhinf_button_tabulka")
        self.trhinf_button_zboziallview = QtWidgets.QPushButton(self.trh)
        self.trhinf_button_zboziallview.setGeometry(QtCore.QRect(370, 80, 231, 25))
        self.trhinf_button_zboziallview.setObjectName("trhinf_button_zboziallview")
        self.trhinf_button_zbozi72 = QtWidgets.QPushButton(self.trh)
        self.trhinf_button_zbozi72.setGeometry(QtCore.QRect(370, 50, 231, 25))
        self.trhinf_button_zbozi72.setObjectName("trhinf_button_zbozi72")
        self.trh_trh = QtWidgets.QTabWidget(self.trh)
        self.trh_trh.setGeometry(QtCore.QRect(10, 150, 961, 331))
        self.trh_trh.setObjectName("trh_trh")
        self.zbozi = QtWidgets.QWidget()
        self.zbozi.setObjectName("zbozi")
        self.trhinf_tabulka = QtWidgets.QTableWidget(self.zbozi)
        self.trhinf_tabulka.setGeometry(QtCore.QRect(0, 0, 601, 251))
        self.trhinf_tabulka.setRowCount(8)
        self.trhinf_tabulka.setColumnCount(9)
        self.trhinf_tabulka.setObjectName("trhinf_tabulka")
        self.trhinf_tabulka.setColumnCount(9)
        self.trhinf_tabulka.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka.setItem(7, 0, item)
        self.trhinf_tabulka.horizontalHeader().setDefaultSectionSize(64)
        self.trhinf_tabulka.horizontalHeader().setMinimumSectionSize(62)
        self.trhinf_tabulka.verticalHeader().setDefaultSectionSize(28)
        self.trhinf_tabulka.verticalHeader().setMinimumSectionSize(19)
        self.trh_trh.addTab(self.zbozi, "")
        self.technologie = QtWidgets.QWidget()
        self.technologie.setObjectName("technologie")
        self.trhinf_tabulka_2 = QtWidgets.QTableWidget(self.technologie)
        self.trhinf_tabulka_2.setGeometry(QtCore.QRect(0, 0, 621, 301))
        self.trhinf_tabulka_2.setRowCount(13)
        self.trhinf_tabulka_2.setColumnCount(9)
        self.trhinf_tabulka_2.setObjectName("trhinf_tabulka_2")
        self.trhinf_tabulka_2.setColumnCount(9)
        self.trhinf_tabulka_2.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhinf_tabulka_2.setItem(12, 0, item)
        self.trhinf_tabulka_2.horizontalHeader().setDefaultSectionSize(64)
        self.trhinf_tabulka_2.horizontalHeader().setMinimumSectionSize(62)
        self.trhinf_tabulka_2.verticalHeader().setDefaultSectionSize(28)
        self.trhinf_tabulka_2.verticalHeader().setMinimumSectionSize(19)
        self.trh_trh.addTab(self.technologie, "")
        self.jidlo_detail = QtWidgets.QWidget()
        self.jidlo_detail.setObjectName("jidlo_detail")
        self.label_23 = QtWidgets.QLabel(self.jidlo_detail)
        self.label_23.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.label_23.setObjectName("label_23")
        self.thrdetail_tabulka1h = QtWidgets.QTableWidget(self.jidlo_detail)
        self.thrdetail_tabulka1h.setGeometry(QtCore.QRect(10, 50, 431, 101))
        self.thrdetail_tabulka1h.setRowCount(2)
        self.thrdetail_tabulka1h.setColumnCount(14)
        self.thrdetail_tabulka1h.setObjectName("thrdetail_tabulka1h")
        self.thrdetail_tabulka1h.setColumnCount(14)
        self.thrdetail_tabulka1h.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h.setItem(1, 0, item)
        self.thrdetail_tabulka1h.horizontalHeader().setDefaultSectionSize(50)
        self.label_40 = QtWidgets.QLabel(self.jidlo_detail)
        self.label_40.setGeometry(QtCore.QRect(300, 160, 161, 21))
        self.label_40.setObjectName("label_40")
        self.trhdetail_graf1h = QtWidgets.QPushButton(self.jidlo_detail)
        self.trhdetail_graf1h.setGeometry(QtCore.QRect(210, 10, 89, 25))
        self.trhdetail_graf1h.setObjectName("trhdetail_graf1h")
        self.trhdetail_all = QtWidgets.QTableWidget(self.jidlo_detail)
        self.trhdetail_all.setGeometry(QtCore.QRect(110, 190, 721, 101))
        self.trhdetail_all.setRowCount(2)
        self.trhdetail_all.setColumnCount(12000)
        self.trhdetail_all.setObjectName("trhdetail_all")
        self.trhdetail_all.setColumnCount(12000)
        self.trhdetail_all.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all.setItem(1, 0, item)
        self.trhdetail_all.horizontalHeader().setDefaultSectionSize(50)
        self.label_25 = QtWidgets.QLabel(self.jidlo_detail)
        self.label_25.setGeometry(QtCore.QRect(530, 10, 161, 21))
        self.label_25.setObjectName("label_25")
        self.trhdetail_graf12 = QtWidgets.QPushButton(self.jidlo_detail)
        self.trhdetail_graf12.setGeometry(QtCore.QRect(710, 10, 89, 25))
        self.trhdetail_graf12.setObjectName("trhdetail_graf12")
        self.trhdetail_12h = QtWidgets.QTableWidget(self.jidlo_detail)
        self.trhdetail_12h.setGeometry(QtCore.QRect(510, 50, 421, 101))
        self.trhdetail_12h.setRowCount(2)
        self.trhdetail_12h.setColumnCount(145)
        self.trhdetail_12h.setObjectName("trhdetail_12h")
        self.trhdetail_12h.setColumnCount(145)
        self.trhdetail_12h.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h.setItem(1, 0, item)
        self.trhdetail_12h.horizontalHeader().setDefaultSectionSize(50)
        self.trhdetail_button_all = QtWidgets.QPushButton(self.jidlo_detail)
        self.trhdetail_button_all.setGeometry(QtCore.QRect(520, 160, 89, 25))
        self.trhdetail_button_all.setObjectName("trhdetail_button_all")
        self.trh_trh.addTab(self.jidlo_detail, "")
        self.ene_detail = QtWidgets.QWidget()
        self.ene_detail.setObjectName("ene_detail")
        self.thrdetail_tabulka1h_2 = QtWidgets.QTableWidget(self.ene_detail)
        self.thrdetail_tabulka1h_2.setGeometry(QtCore.QRect(10, 50, 431, 101))
        self.thrdetail_tabulka1h_2.setRowCount(2)
        self.thrdetail_tabulka1h_2.setColumnCount(14)
        self.thrdetail_tabulka1h_2.setObjectName("thrdetail_tabulka1h_2")
        self.thrdetail_tabulka1h_2.setColumnCount(14)
        self.thrdetail_tabulka1h_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_2.setItem(1, 0, item)
        self.thrdetail_tabulka1h_2.horizontalHeader().setDefaultSectionSize(50)
        self.label_41 = QtWidgets.QLabel(self.ene_detail)
        self.label_41.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.label_41.setObjectName("label_41")
        self.trhdetail_graf1h_2 = QtWidgets.QPushButton(self.ene_detail)
        self.trhdetail_graf1h_2.setGeometry(QtCore.QRect(210, 10, 89, 25))
        self.trhdetail_graf1h_2.setObjectName("trhdetail_graf1h_2")
        self.trhdetail_all_2 = QtWidgets.QTableWidget(self.ene_detail)
        self.trhdetail_all_2.setGeometry(QtCore.QRect(110, 190, 721, 101))
        self.trhdetail_all_2.setRowCount(2)
        self.trhdetail_all_2.setColumnCount(12000)
        self.trhdetail_all_2.setObjectName("trhdetail_all_2")
        self.trhdetail_all_2.setColumnCount(12000)
        self.trhdetail_all_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_2.setItem(1, 0, item)
        self.trhdetail_all_2.horizontalHeader().setDefaultSectionSize(50)
        self.trhdetail_graf12_2 = QtWidgets.QPushButton(self.ene_detail)
        self.trhdetail_graf12_2.setGeometry(QtCore.QRect(710, 10, 89, 25))
        self.trhdetail_graf12_2.setObjectName("trhdetail_graf12_2")
        self.label_42 = QtWidgets.QLabel(self.ene_detail)
        self.label_42.setGeometry(QtCore.QRect(300, 160, 161, 21))
        self.label_42.setObjectName("label_42")
        self.trhdetail_button_all_2 = QtWidgets.QPushButton(self.ene_detail)
        self.trhdetail_button_all_2.setGeometry(QtCore.QRect(520, 160, 89, 25))
        self.trhdetail_button_all_2.setObjectName("trhdetail_button_all_2")
        self.label_43 = QtWidgets.QLabel(self.ene_detail)
        self.label_43.setGeometry(QtCore.QRect(530, 10, 161, 21))
        self.label_43.setObjectName("label_43")
        self.trhdetail_12h_2 = QtWidgets.QTableWidget(self.ene_detail)
        self.trhdetail_12h_2.setGeometry(QtCore.QRect(510, 50, 421, 101))
        self.trhdetail_12h_2.setRowCount(2)
        self.trhdetail_12h_2.setColumnCount(145)
        self.trhdetail_12h_2.setObjectName("trhdetail_12h_2")
        self.trhdetail_12h_2.setColumnCount(145)
        self.trhdetail_12h_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_2.setItem(1, 0, item)
        self.trhdetail_12h_2.horizontalHeader().setDefaultSectionSize(50)
        self.trh_trh.addTab(self.ene_detail, "")
        self.voj_detail = QtWidgets.QWidget()
        self.voj_detail.setObjectName("voj_detail")
        self.thrdetail_tabulka1h_3 = QtWidgets.QTableWidget(self.voj_detail)
        self.thrdetail_tabulka1h_3.setGeometry(QtCore.QRect(20, 50, 431, 101))
        self.thrdetail_tabulka1h_3.setRowCount(2)
        self.thrdetail_tabulka1h_3.setColumnCount(14)
        self.thrdetail_tabulka1h_3.setObjectName("thrdetail_tabulka1h_3")
        self.thrdetail_tabulka1h_3.setColumnCount(14)
        self.thrdetail_tabulka1h_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_3.setItem(1, 0, item)
        self.thrdetail_tabulka1h_3.horizontalHeader().setDefaultSectionSize(50)
        self.label_44 = QtWidgets.QLabel(self.voj_detail)
        self.label_44.setGeometry(QtCore.QRect(30, 10, 171, 21))
        self.label_44.setObjectName("label_44")
        self.trhdetail_graf1h_3 = QtWidgets.QPushButton(self.voj_detail)
        self.trhdetail_graf1h_3.setGeometry(QtCore.QRect(220, 10, 89, 25))
        self.trhdetail_graf1h_3.setObjectName("trhdetail_graf1h_3")
        self.trhdetail_all_3 = QtWidgets.QTableWidget(self.voj_detail)
        self.trhdetail_all_3.setGeometry(QtCore.QRect(120, 190, 721, 101))
        self.trhdetail_all_3.setRowCount(2)
        self.trhdetail_all_3.setColumnCount(12000)
        self.trhdetail_all_3.setObjectName("trhdetail_all_3")
        self.trhdetail_all_3.setColumnCount(12000)
        self.trhdetail_all_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_3.setItem(1, 0, item)
        self.trhdetail_all_3.horizontalHeader().setDefaultSectionSize(50)
        self.trhdetail_graf12_3 = QtWidgets.QPushButton(self.voj_detail)
        self.trhdetail_graf12_3.setGeometry(QtCore.QRect(720, 10, 89, 25))
        self.trhdetail_graf12_3.setObjectName("trhdetail_graf12_3")
        self.label_45 = QtWidgets.QLabel(self.voj_detail)
        self.label_45.setGeometry(QtCore.QRect(310, 160, 161, 21))
        self.label_45.setObjectName("label_45")
        self.trhdetail_button_all_3 = QtWidgets.QPushButton(self.voj_detail)
        self.trhdetail_button_all_3.setGeometry(QtCore.QRect(530, 160, 89, 25))
        self.trhdetail_button_all_3.setObjectName("trhdetail_button_all_3")
        self.label_46 = QtWidgets.QLabel(self.voj_detail)
        self.label_46.setGeometry(QtCore.QRect(540, 10, 161, 21))
        self.label_46.setObjectName("label_46")
        self.trhdetail_12h_3 = QtWidgets.QTableWidget(self.voj_detail)
        self.trhdetail_12h_3.setGeometry(QtCore.QRect(520, 50, 421, 101))
        self.trhdetail_12h_3.setRowCount(2)
        self.trhdetail_12h_3.setColumnCount(145)
        self.trhdetail_12h_3.setObjectName("trhdetail_12h_3")
        self.trhdetail_12h_3.setColumnCount(145)
        self.trhdetail_12h_3.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_3.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_3.setItem(1, 0, item)
        self.trhdetail_12h_3.horizontalHeader().setDefaultSectionSize(50)
        self.trh_trh.addTab(self.voj_detail, "")
        self.tanky_detail = QtWidgets.QWidget()
        self.tanky_detail.setObjectName("tanky_detail")
        self.thrdetail_tabulka1h_4 = QtWidgets.QTableWidget(self.tanky_detail)
        self.thrdetail_tabulka1h_4.setGeometry(QtCore.QRect(20, 50, 431, 101))
        self.thrdetail_tabulka1h_4.setRowCount(2)
        self.thrdetail_tabulka1h_4.setColumnCount(14)
        self.thrdetail_tabulka1h_4.setObjectName("thrdetail_tabulka1h_4")
        self.thrdetail_tabulka1h_4.setColumnCount(14)
        self.thrdetail_tabulka1h_4.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_4.setItem(1, 0, item)
        self.thrdetail_tabulka1h_4.horizontalHeader().setDefaultSectionSize(50)
        self.label_47 = QtWidgets.QLabel(self.tanky_detail)
        self.label_47.setGeometry(QtCore.QRect(30, 10, 171, 21))
        self.label_47.setObjectName("label_47")
        self.trhdetail_graf1h_4 = QtWidgets.QPushButton(self.tanky_detail)
        self.trhdetail_graf1h_4.setGeometry(QtCore.QRect(220, 10, 89, 25))
        self.trhdetail_graf1h_4.setObjectName("trhdetail_graf1h_4")
        self.trhdetail_all_4 = QtWidgets.QTableWidget(self.tanky_detail)
        self.trhdetail_all_4.setGeometry(QtCore.QRect(120, 190, 721, 101))
        self.trhdetail_all_4.setRowCount(2)
        self.trhdetail_all_4.setColumnCount(12000)
        self.trhdetail_all_4.setObjectName("trhdetail_all_4")
        self.trhdetail_all_4.setColumnCount(12000)
        self.trhdetail_all_4.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_4.setItem(1, 0, item)
        self.trhdetail_all_4.horizontalHeader().setDefaultSectionSize(50)
        self.trhdetail_graf12_4 = QtWidgets.QPushButton(self.tanky_detail)
        self.trhdetail_graf12_4.setGeometry(QtCore.QRect(720, 10, 89, 25))
        self.trhdetail_graf12_4.setObjectName("trhdetail_graf12_4")
        self.label_48 = QtWidgets.QLabel(self.tanky_detail)
        self.label_48.setGeometry(QtCore.QRect(310, 160, 161, 21))
        self.label_48.setObjectName("label_48")
        self.trhdetail_button_all_4 = QtWidgets.QPushButton(self.tanky_detail)
        self.trhdetail_button_all_4.setGeometry(QtCore.QRect(530, 160, 89, 25))
        self.trhdetail_button_all_4.setObjectName("trhdetail_button_all_4")
        self.label_49 = QtWidgets.QLabel(self.tanky_detail)
        self.label_49.setGeometry(QtCore.QRect(540, 10, 161, 21))
        self.label_49.setObjectName("label_49")
        self.trhdetail_12h_4 = QtWidgets.QTableWidget(self.tanky_detail)
        self.trhdetail_12h_4.setGeometry(QtCore.QRect(520, 50, 421, 101))
        self.trhdetail_12h_4.setRowCount(2)
        self.trhdetail_12h_4.setColumnCount(145)
        self.trhdetail_12h_4.setObjectName("trhdetail_12h_4")
        self.trhdetail_12h_4.setColumnCount(145)
        self.trhdetail_12h_4.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_4.setItem(1, 0, item)
        self.trhdetail_12h_4.horizontalHeader().setDefaultSectionSize(50)
        self.trh_trh.addTab(self.tanky_detail, "")
        self.stihy_detail = QtWidgets.QWidget()
        self.stihy_detail.setObjectName("stihy_detail")
        self.thrdetail_tabulka1h_5 = QtWidgets.QTableWidget(self.stihy_detail)
        self.thrdetail_tabulka1h_5.setGeometry(QtCore.QRect(10, 50, 431, 101))
        self.thrdetail_tabulka1h_5.setRowCount(2)
        self.thrdetail_tabulka1h_5.setColumnCount(14)
        self.thrdetail_tabulka1h_5.setObjectName("thrdetail_tabulka1h_5")
        self.thrdetail_tabulka1h_5.setColumnCount(14)
        self.thrdetail_tabulka1h_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_5.setItem(1, 0, item)
        self.thrdetail_tabulka1h_5.horizontalHeader().setDefaultSectionSize(50)
        self.label_50 = QtWidgets.QLabel(self.stihy_detail)
        self.label_50.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.label_50.setObjectName("label_50")
        self.trhdetail_graf1h_5 = QtWidgets.QPushButton(self.stihy_detail)
        self.trhdetail_graf1h_5.setGeometry(QtCore.QRect(210, 10, 89, 25))
        self.trhdetail_graf1h_5.setObjectName("trhdetail_graf1h_5")
        self.trhdetail_all_5 = QtWidgets.QTableWidget(self.stihy_detail)
        self.trhdetail_all_5.setGeometry(QtCore.QRect(110, 190, 721, 101))
        self.trhdetail_all_5.setRowCount(2)
        self.trhdetail_all_5.setColumnCount(12000)
        self.trhdetail_all_5.setObjectName("trhdetail_all_5")
        self.trhdetail_all_5.setColumnCount(12000)
        self.trhdetail_all_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_5.setItem(1, 0, item)
        self.trhdetail_all_5.horizontalHeader().setDefaultSectionSize(50)
        self.trhdetail_graf12_5 = QtWidgets.QPushButton(self.stihy_detail)
        self.trhdetail_graf12_5.setGeometry(QtCore.QRect(710, 10, 89, 25))
        self.trhdetail_graf12_5.setObjectName("trhdetail_graf12_5")
        self.label_51 = QtWidgets.QLabel(self.stihy_detail)
        self.label_51.setGeometry(QtCore.QRect(300, 160, 161, 21))
        self.label_51.setObjectName("label_51")
        self.trhdetail_button_all_5 = QtWidgets.QPushButton(self.stihy_detail)
        self.trhdetail_button_all_5.setGeometry(QtCore.QRect(520, 160, 89, 25))
        self.trhdetail_button_all_5.setObjectName("trhdetail_button_all_5")
        self.label_52 = QtWidgets.QLabel(self.stihy_detail)
        self.label_52.setGeometry(QtCore.QRect(530, 10, 161, 21))
        self.label_52.setObjectName("label_52")
        self.trhdetail_12h_5 = QtWidgets.QTableWidget(self.stihy_detail)
        self.trhdetail_12h_5.setGeometry(QtCore.QRect(510, 50, 421, 101))
        self.trhdetail_12h_5.setRowCount(2)
        self.trhdetail_12h_5.setColumnCount(145)
        self.trhdetail_12h_5.setObjectName("trhdetail_12h_5")
        self.trhdetail_12h_5.setColumnCount(145)
        self.trhdetail_12h_5.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_5.setItem(1, 0, item)
        self.trhdetail_12h_5.horizontalHeader().setDefaultSectionSize(50)
        self.trh_trh.addTab(self.stihy_detail, "")
        self.bunkry_detail = QtWidgets.QWidget()
        self.bunkry_detail.setObjectName("bunkry_detail")
        self.thrdetail_tabulka1h_6 = QtWidgets.QTableWidget(self.bunkry_detail)
        self.thrdetail_tabulka1h_6.setGeometry(QtCore.QRect(10, 50, 431, 101))
        self.thrdetail_tabulka1h_6.setRowCount(2)
        self.thrdetail_tabulka1h_6.setColumnCount(14)
        self.thrdetail_tabulka1h_6.setObjectName("thrdetail_tabulka1h_6")
        self.thrdetail_tabulka1h_6.setColumnCount(14)
        self.thrdetail_tabulka1h_6.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_6.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_6.setItem(1, 0, item)
        self.thrdetail_tabulka1h_6.horizontalHeader().setDefaultSectionSize(50)
        self.label_53 = QtWidgets.QLabel(self.bunkry_detail)
        self.label_53.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.label_53.setObjectName("label_53")
        self.trhdetail_graf1h_6 = QtWidgets.QPushButton(self.bunkry_detail)
        self.trhdetail_graf1h_6.setGeometry(QtCore.QRect(210, 10, 89, 25))
        self.trhdetail_graf1h_6.setObjectName("trhdetail_graf1h_6")
        self.trhdetail_all_6 = QtWidgets.QTableWidget(self.bunkry_detail)
        self.trhdetail_all_6.setGeometry(QtCore.QRect(110, 190, 721, 101))
        self.trhdetail_all_6.setRowCount(2)
        self.trhdetail_all_6.setColumnCount(12000)
        self.trhdetail_all_6.setObjectName("trhdetail_all_6")
        self.trhdetail_all_6.setColumnCount(12000)
        self.trhdetail_all_6.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_6.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_6.setItem(1, 0, item)
        self.trhdetail_all_6.horizontalHeader().setDefaultSectionSize(50)
        self.trhdetail_graf12_6 = QtWidgets.QPushButton(self.bunkry_detail)
        self.trhdetail_graf12_6.setGeometry(QtCore.QRect(710, 10, 89, 25))
        self.trhdetail_graf12_6.setObjectName("trhdetail_graf12_6")
        self.label_54 = QtWidgets.QLabel(self.bunkry_detail)
        self.label_54.setGeometry(QtCore.QRect(300, 160, 161, 21))
        self.label_54.setObjectName("label_54")
        self.trhdetail_button_all_6 = QtWidgets.QPushButton(self.bunkry_detail)
        self.trhdetail_button_all_6.setGeometry(QtCore.QRect(520, 160, 89, 25))
        self.trhdetail_button_all_6.setObjectName("trhdetail_button_all_6")
        self.label_55 = QtWidgets.QLabel(self.bunkry_detail)
        self.label_55.setGeometry(QtCore.QRect(530, 10, 161, 21))
        self.label_55.setObjectName("label_55")
        self.trhdetail_12h_6 = QtWidgets.QTableWidget(self.bunkry_detail)
        self.trhdetail_12h_6.setGeometry(QtCore.QRect(510, 50, 421, 101))
        self.trhdetail_12h_6.setRowCount(2)
        self.trhdetail_12h_6.setColumnCount(145)
        self.trhdetail_12h_6.setObjectName("trhdetail_12h_6")
        self.trhdetail_12h_6.setColumnCount(145)
        self.trhdetail_12h_6.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_6.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_6.setItem(1, 0, item)
        self.trhdetail_12h_6.horizontalHeader().setDefaultSectionSize(50)
        self.trh_trh.addTab(self.bunkry_detail, "")
        self.mechy_detail = QtWidgets.QWidget()
        self.mechy_detail.setObjectName("mechy_detail")
        self.thrdetail_tabulka1h_7 = QtWidgets.QTableWidget(self.mechy_detail)
        self.thrdetail_tabulka1h_7.setGeometry(QtCore.QRect(10, 50, 431, 101))
        self.thrdetail_tabulka1h_7.setRowCount(2)
        self.thrdetail_tabulka1h_7.setColumnCount(14)
        self.thrdetail_tabulka1h_7.setObjectName("thrdetail_tabulka1h_7")
        self.thrdetail_tabulka1h_7.setColumnCount(14)
        self.thrdetail_tabulka1h_7.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_7.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thrdetail_tabulka1h_7.setItem(1, 0, item)
        self.thrdetail_tabulka1h_7.horizontalHeader().setDefaultSectionSize(50)
        self.label_56 = QtWidgets.QLabel(self.mechy_detail)
        self.label_56.setGeometry(QtCore.QRect(20, 10, 171, 21))
        self.label_56.setObjectName("label_56")
        self.trhdetail_graf1h_7 = QtWidgets.QPushButton(self.mechy_detail)
        self.trhdetail_graf1h_7.setGeometry(QtCore.QRect(210, 10, 89, 25))
        self.trhdetail_graf1h_7.setObjectName("trhdetail_graf1h_7")
        self.trhdetail_all_7 = QtWidgets.QTableWidget(self.mechy_detail)
        self.trhdetail_all_7.setGeometry(QtCore.QRect(110, 190, 721, 101))
        self.trhdetail_all_7.setRowCount(2)
        self.trhdetail_all_7.setColumnCount(12000)
        self.trhdetail_all_7.setObjectName("trhdetail_all_7")
        self.trhdetail_all_7.setColumnCount(12000)
        self.trhdetail_all_7.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_7.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_all_7.setItem(1, 0, item)
        self.trhdetail_all_7.horizontalHeader().setDefaultSectionSize(50)
        self.trhdetail_graf12_7 = QtWidgets.QPushButton(self.mechy_detail)
        self.trhdetail_graf12_7.setGeometry(QtCore.QRect(710, 10, 89, 25))
        self.trhdetail_graf12_7.setObjectName("trhdetail_graf12_7")
        self.label_57 = QtWidgets.QLabel(self.mechy_detail)
        self.label_57.setGeometry(QtCore.QRect(300, 160, 161, 21))
        self.label_57.setObjectName("label_57")
        self.trhdetail_button_all_7 = QtWidgets.QPushButton(self.mechy_detail)
        self.trhdetail_button_all_7.setGeometry(QtCore.QRect(520, 160, 89, 25))
        self.trhdetail_button_all_7.setObjectName("trhdetail_button_all_7")
        self.label_58 = QtWidgets.QLabel(self.mechy_detail)
        self.label_58.setGeometry(QtCore.QRect(530, 10, 161, 21))
        self.label_58.setObjectName("label_58")
        self.trhdetail_12h_7 = QtWidgets.QTableWidget(self.mechy_detail)
        self.trhdetail_12h_7.setGeometry(QtCore.QRect(510, 50, 421, 101))
        self.trhdetail_12h_7.setRowCount(2)
        self.trhdetail_12h_7.setColumnCount(145)
        self.trhdetail_12h_7.setObjectName("trhdetail_12h_7")
        self.trhdetail_12h_7.setColumnCount(145)
        self.trhdetail_12h_7.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_7.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trhdetail_12h_7.setItem(1, 0, item)
        self.trhdetail_12h_7.horizontalHeader().setDefaultSectionSize(50)
        self.trh_trh.addTab(self.mechy_detail, "")
        self.label_15 = QtWidgets.QLabel(self.trh)
        self.label_15.setGeometry(QtCore.QRect(460, 30, 41, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.trh)
        self.label_16.setGeometry(QtCore.QRect(780, 30, 91, 17))
        self.label_16.setObjectName("label_16")
        self.thrinf_button_tech72 = QtWidgets.QPushButton(self.trh)
        self.thrinf_button_tech72.setGeometry(QtCore.QRect(710, 50, 231, 25))
        self.thrinf_button_tech72.setObjectName("thrinf_button_tech72")
        self.trhinf_button_techallview = QtWidgets.QPushButton(self.trh)
        self.trhinf_button_techallview.setGeometry(QtCore.QRect(710, 80, 231, 25))
        self.trhinf_button_techallview.setObjectName("trhinf_button_techallview")
        self.line_9 = QtWidgets.QFrame(self.trh)
        self.line_9.setGeometry(QtCore.QRect(260, 130, 711, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.tabWidget.addTab(self.trh, "")
        self.trh_preprodej = QtWidgets.QWidget()
        self.trh_preprodej.setObjectName("trh_preprodej")
        self.svtrh_kolikchciutratit = QtWidgets.QLineEdit(self.trh_preprodej)
        self.svtrh_kolikchciutratit.setGeometry(QtCore.QRect(800, 120, 113, 21))
        self.svtrh_kolikchciutratit.setText("")
        self.svtrh_kolikchciutratit.setObjectName("svtrh_kolikchciutratit")
        self.line_5 = QtWidgets.QFrame(self.trh_preprodej)
        self.line_5.setGeometry(QtCore.QRect(820, 35, 141, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.domtrh_button_startpreprodej = QtWidgets.QPushButton(self.trh_preprodej)
        self.domtrh_button_startpreprodej.setGeometry(QtCore.QRect(480, 150, 89, 25))
        self.domtrh_button_startpreprodej.setObjectName("domtrh_button_startpreprodej")
        self.svtr_mincastka = QtWidgets.QLineEdit(self.trh_preprodej)
        self.svtr_mincastka.setGeometry(QtCore.QRect(800, 60, 113, 21))
        self.svtr_mincastka.setText("")
        self.svtr_mincastka.setObjectName("svtr_mincastka")
        self.trh_checkBox_bunkry = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_bunkry.setGeometry(QtCore.QRect(150, 120, 92, 23))
        self.trh_checkBox_bunkry.setObjectName("trh_checkBox_bunkry")
        self.label_18 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_18.setGeometry(QtCore.QRect(320, 90, 221, 21))
        self.label_18.setObjectName("label_18")
        self.line_4 = QtWidgets.QFrame(self.trh_preprodej)
        self.line_4.setGeometry(QtCore.QRect(490, 35, 81, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.trh_checkBox_jidlo = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_jidlo.setGeometry(QtCore.QRect(150, 80, 92, 23))
        self.trh_checkBox_jidlo.setObjectName("trh_checkBox_jidlo")
        self.label_22 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_22.setGeometry(QtCore.QRect(20, 40, 141, 17))
        self.label_22.setObjectName("label_22")
        self.line_3 = QtWidgets.QFrame(self.trh_preprodej)
        self.line_3.setGeometry(QtCore.QRect(160, 35, 71, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.domtrh_navyseniprodceny = QtWidgets.QLineEdit(self.trh_preprodej)
        self.domtrh_navyseniprodceny.setGeometry(QtCore.QRect(460, 90, 113, 20))
        self.domtrh_navyseniprodceny.setText("")
        self.domtrh_navyseniprodceny.setObjectName("domtrh_navyseniprodceny")
        self.label_30 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_30.setGeometry(QtCore.QRect(320, 60, 141, 21))
        self.label_30.setObjectName("label_30")
        self.label_2 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_2.setGeometry(QtCore.QRect(640, 40, 181, 17))
        self.label_2.setObjectName("label_2")
        self.svtrh_button_startprepodej = QtWidgets.QPushButton(self.trh_preprodej)
        self.svtrh_button_startprepodej.setGeometry(QtCore.QRect(820, 150, 89, 25))
        self.svtrh_button_startprepodej.setObjectName("svtrh_button_startprepodej")
        self.label_28 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_28.setGeometry(QtCore.QRect(310, 40, 171, 17))
        self.label_28.setObjectName("label_28")
        self.label_6 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_6.setGeometry(QtCore.QRect(660, 120, 141, 17))
        self.label_6.setObjectName("label_6")
        self.trh_checkBox_energie = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_energie.setGeometry(QtCore.QRect(40, 80, 92, 23))
        self.trh_checkBox_energie.setObjectName("trh_checkBox_energie")
        self.line_7 = QtWidgets.QFrame(self.trh_preprodej)
        self.line_7.setGeometry(QtCore.QRect(70, 10, 891, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.trh_checkBox_tanky = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_tanky.setGeometry(QtCore.QRect(150, 100, 92, 23))
        self.trh_checkBox_tanky.setObjectName("trh_checkBox_tanky")
        self.domtrh_kolikchciutratit = QtWidgets.QLineEdit(self.trh_preprodej)
        self.domtrh_kolikchciutratit.setGeometry(QtCore.QRect(460, 120, 113, 21))
        self.domtrh_kolikchciutratit.setText("")
        self.domtrh_kolikchciutratit.setObjectName("domtrh_kolikchciutratit")
        self.label_4 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_4.setGeometry(QtCore.QRect(660, 90, 131, 17))
        self.label_4.setObjectName("label_4")
        self.label_24 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_24.setGeometry(QtCore.QRect(0, 10, 71, 17))
        self.label_24.setObjectName("label_24")
        self.trh_checkBox_stihacky = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_stihacky.setGeometry(QtCore.QRect(40, 120, 92, 23))
        self.trh_checkBox_stihacky.setObjectName("trh_checkBox_stihacky")
        self.trh_checkBox_vojaci = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_vojaci.setGeometry(QtCore.QRect(40, 100, 92, 23))
        self.trh_checkBox_vojaci.setObjectName("trh_checkBox_vojaci")
        self.label_3 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_3.setGeometry(QtCore.QRect(660, 60, 141, 17))
        self.label_3.setObjectName("label_3")
        self.trh_checkBox_all = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_all.setGeometry(QtCore.QRect(30, 60, 92, 23))
        self.trh_checkBox_all.setObjectName("trh_checkBox_all")
        self.svtrh_navyseniprodejniceny = QtWidgets.QLineEdit(self.trh_preprodej)
        self.svtrh_navyseniprodejniceny.setGeometry(QtCore.QRect(800, 90, 113, 21))
        self.svtrh_navyseniprodejniceny.setText("")
        self.svtrh_navyseniprodejniceny.setObjectName("svtrh_navyseniprodejniceny")
        self.trh_checkBox_mechy = QtWidgets.QCheckBox(self.trh_preprodej)
        self.trh_checkBox_mechy.setGeometry(QtCore.QRect(40, 140, 92, 23))
        self.trh_checkBox_mechy.setObjectName("trh_checkBox_mechy")
        self.label_5 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_5.setGeometry(QtCore.QRect(320, 120, 111, 17))
        self.label_5.setObjectName("label_5")
        self.domtrh_mincastka = QtWidgets.QLineEdit(self.trh_preprodej)
        self.domtrh_mincastka.setGeometry(QtCore.QRect(460, 60, 113, 21))
        self.domtrh_mincastka.setText("")
        self.domtrh_mincastka.setObjectName("domtrh_mincastka")
        self.label_39 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_39.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.label_39.setObjectName("label_39")
        self.line_19 = QtWidgets.QFrame(self.trh_preprodej)
        self.line_19.setGeometry(QtCore.QRect(110, 481, 861, 31))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.trhpreprodej_whathap = QtWidgets.QTextEdit(self.trh_preprodej)
        self.trhpreprodej_whathap.setGeometry(QtCore.QRect(40, 510, 921, 241))
        self.trhpreprodej_whathap.setObjectName("trhpreprodej_whathap")
        self.label_33 = QtWidgets.QLabel(self.trh_preprodej)
        self.label_33.setGeometry(QtCore.QRect(30, 210, 91, 17))
        self.label_33.setObjectName("label_33")
        self.line_20 = QtWidgets.QFrame(self.trh_preprodej)
        self.line_20.setGeometry(QtCore.QRect(120, 205, 851, 31))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.tabWidget.addTab(self.trh_preprodej, "")
        # region Rozvědka
        self.rozvedka = QtWidgets.QWidget()
        self.rozvedka.setObjectName("rozvedka")
        self.rozv_pocetzemi_2 = QtWidgets.QLineEdit(self.rozvedka)
        self.rozv_pocetzemi_2.setGeometry(QtCore.QRect(290, 190, 51, 25))
        self.rozv_pocetzemi_2.setObjectName("rozv_pocetzemi_2")
        self.label_27 = QtWidgets.QLabel(self.rozvedka)
        self.label_27.setGeometry(QtCore.QRect(70, 150, 151, 21))
        self.label_27.setObjectName("label_27")
        self.label_17 = QtWidgets.QLabel(self.rozvedka)
        self.label_17.setGeometry(QtCore.QRect(70, 120, 191, 21))
        self.label_17.setObjectName("label_17")
        self.label_26 = QtWidgets.QLabel(self.rozvedka)
        self.label_26.setGeometry(QtCore.QRect(70, 190, 191, 21))
        self.label_26.setObjectName("label_26")
        self.rozvedka_button_start = QtWidgets.QPushButton(self.rozvedka)  # Rozvědka start button
        self.rozvedka_button_start.setGeometry(QtCore.QRect(270, 280, 89, 25))
        self.rozvedka_button_start.setObjectName("rozvedka_button_start")
        self.rozv_rovnouzemivykrast_2 = QtWidgets.QCheckBox(self.rozvedka)
        self.rozv_rovnouzemivykrast_2.setGeometry(QtCore.QRect(60, 90, 241, 23))
        self.rozv_rovnouzemivykrast_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rozv_rovnouzemivykrast_2.setObjectName("rozv_rovnouzemivykrast_2")
        self.line_10 = QtWidgets.QFrame(self.rozvedka)
        self.line_10.setGeometry(QtCore.QRect(80, 10, 891, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.rozv_num_unsuc_2 = QtWidgets.QSpinBox(self.rozvedka)
        self.rozv_num_unsuc_2.setGeometry(QtCore.QRect(290, 120, 48, 21))
        self.rozv_num_unsuc_2.setObjectName("rozv_num_unsuc_2")
        self.rozv_num_pokusu_2 = QtWidgets.QSpinBox(self.rozvedka)
        self.rozv_num_pokusu_2.setGeometry(QtCore.QRect(290, 150, 48, 21))
        self.rozv_num_pokusu_2.setObjectName("rozv_num_pokusu_2")
        self.rozv_vyhledatzeme_2 = QtWidgets.QCheckBox(self.rozvedka)  # Rozvědka vyhledávání zemí
        self.rozv_vyhledatzeme_2.setEnabled(True)
        self.rozv_vyhledatzeme_2.setGeometry(QtCore.QRect(70, 60, 231, 23))
        self.rozv_vyhledatzeme_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rozv_vyhledatzeme_2.setObjectName("rozv_vyhledatzeme_2")
        self.label_19 = QtWidgets.QLabel(self.rozvedka)
        self.label_19.setGeometry(QtCore.QRect(10, 6, 67, 21))
        self.label_19.setObjectName("label_19")
        self.label_8 = QtWidgets.QLabel(self.rozvedka)
        self.label_8.setGeometry(QtCore.QRect(460, 40, 67, 17))
        self.label_8.setObjectName("label_8")
        self.rozvedka_top10 = QtWidgets.QTextEdit(self.rozvedka)
        self.rozvedka_top10.setGeometry(QtCore.QRect(480, 70, 481, 231))
        self.rozvedka_top10.setObjectName("rozvedka_top10")
        self.rozvedka_whathap = QtWidgets.QTextEdit(self.rozvedka)
        self.rozvedka_whathap.setGeometry(QtCore.QRect(40, 510, 921, 241))
        self.rozvedka_whathap.setObjectName("rozvedka_whathap")
        self.line_14 = QtWidgets.QFrame(self.rozvedka)
        self.line_14.setGeometry(QtCore.QRect(110, 481, 851, 31))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_34 = QtWidgets.QLabel(self.rozvedka)
        self.label_34.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.label_34.setObjectName("label_34")
        self.label_9 = QtWidgets.QLabel(self.rozvedka)
        self.label_9.setGeometry(QtCore.QRect(50, 40, 67, 17))
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.rozvedka)
        self.line.setGeometry(QtCore.QRect(130, 35, 281, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.rozvedka)
        self.line_2.setGeometry(QtCore.QRect(517, 29, 451, 41))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.rozvedka, "")
        # endregion
        self.war = QtWidgets.QWidget()
        self.war.setObjectName("war")
        self.label_7 = QtWidgets.QLabel(self.war)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 251, 17))
        self.label_7.setObjectName("label_7")
        self.label_36 = QtWidgets.QLabel(self.war)
        self.label_36.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.label_36.setObjectName("label_36")
        self.line_16 = QtWidgets.QFrame(self.war)
        self.line_16.setGeometry(QtCore.QRect(110, 481, 851, 31))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.textEdit_6 = QtWidgets.QTextEdit(self.war)
        self.textEdit_6.setGeometry(QtCore.QRect(40, 510, 921, 241))
        self.textEdit_6.setObjectName("textEdit_6")
        self.tabWidget.addTab(self.war, "")
        self.technology = QtWidgets.QWidget()
        self.technology.setObjectName("technology")
        self.label = QtWidgets.QLabel(self.technology)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 17))
        self.label.setObjectName("label")
        self.label_37 = QtWidgets.QLabel(self.technology)
        self.label_37.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.label_37.setObjectName("label_37")
        self.line_17 = QtWidgets.QFrame(self.technology)
        self.line_17.setGeometry(QtCore.QRect(110, 481, 861, 31))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.textEdit_7 = QtWidgets.QTextEdit(self.technology)
        self.textEdit_7.setGeometry(QtCore.QRect(40, 510, 921, 241))
        self.textEdit_7.setObjectName("textEdit_7")
        self.tabWidget.addTab(self.technology, "")
        self.archiv = QtWidgets.QWidget()
        self.archiv.setObjectName("archiv")
        self.label_38 = QtWidgets.QLabel(self.archiv)
        self.label_38.setGeometry(QtCore.QRect(10, 480, 111, 31))
        self.label_38.setObjectName("label_38")
        self.line_18 = QtWidgets.QFrame(self.archiv)
        self.line_18.setGeometry(QtCore.QRect(110, 481, 861, 31))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.archiv_whathap = QtWidgets.QTextEdit(self.archiv)
        self.archiv_whathap.setGeometry(QtCore.QRect(40, 510, 931, 241))
        self.archiv_whathap.setObjectName("archiv_whathap")
        self.line_8 = QtWidgets.QFrame(self.archiv)
        self.line_8.setGeometry(QtCore.QRect(60, 18, 341, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.archiv_button_save_archiv = QtWidgets.QPushButton(self.archiv)
        self.archiv_button_save_archiv.setGeometry(QtCore.QRect(290, 110, 89, 25))
        self.archiv_button_save_archiv.setObjectName("archiv_button_save_archiv")
        self.label_29 = QtWidgets.QLabel(self.archiv)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 67, 31))
        self.label_29.setObjectName("label_29")
        self.archiv_toexcel_2 = QtWidgets.QCheckBox(self.archiv)
        self.archiv_toexcel_2.setGeometry(QtCore.QRect(30, 40, 211, 23))
        self.archiv_toexcel_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.archiv_toexcel_2.setObjectName("archiv_toexcel_2")
        self.archiv_best_2 = QtWidgets.QCheckBox(self.archiv)
        self.archiv_best_2.setGeometry(QtCore.QRect(30, 60, 251, 23))
        self.archiv_best_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.archiv_best_2.setObjectName("archiv_best_2")
        self.label_11 = QtWidgets.QLabel(self.archiv)
        self.label_11.setGeometry(QtCore.QRect(460, 20, 181, 17))
        self.label_11.setObjectName("label_11")
        self.line_13 = QtWidgets.QFrame(self.archiv)
        self.line_13.setGeometry(QtCore.QRect(650, 15, 321, 31))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.archiv_button_saveexcel_trh = QtWidgets.QPushButton(self.archiv)
        self.archiv_button_saveexcel_trh.setGeometry(QtCore.QRect(750, 100, 89, 25))
        self.archiv_button_saveexcel_trh.setObjectName("archiv_button_saveexcel_trh")
        self.label_12 = QtWidgets.QLabel(self.archiv)
        self.label_12.setGeometry(QtCore.QRect(490, 50, 401, 17))
        self.label_12.setObjectName("label_12")
        self.tabWidget.addTab(self.archiv, "")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        Tabulky.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tabulky)
        self.tabWidget.setCurrentIndex(1)
        self.trh_trh.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Tabulky)

    def retranslateUi(self, Tabulky):
        Tabulky.setWindowTitle(QtWidgets.QApplication.translate("Tabulky", "WBGS", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("Tabulky", "Země:", None, -1))
        self.number_land.setItemText(0, QtWidgets.QApplication.translate("Tabulky", "Zem 1", None, -1))
        self.number_land.setItemText(1, QtWidgets.QApplication.translate("Tabulky", "Zem 2", None, -1))
        self.number_land.setItemText(2, QtWidgets.QApplication.translate("Tabulky", "Zem 3 //Nefunknčí", None, -1))
        self.number_land.setItemText(3, QtWidgets.QApplication.translate("Tabulky", "Zem 4 //NEfunčkní", None, -1))
        self.password_2.setText(QtWidgets.QApplication.translate("Tabulky", "Heslo:", None, -1))
        self.login_2.setText(QtWidgets.QApplication.translate("Tabulky", "LogIn:", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Tabulky", "Settings", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("Tabulky", "Cesta k driveru:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Tabulky", "Info", None, -1))
        self.textEdit.setHtml(QtWidgets.QApplication.translate("Tabulky",
                                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                               "p, li { white-space: pre-wrap; }\n"
                                                               "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Zatím funguje:</span> Nic<br /><span style=\" font-weight:600;\">Zatím nefunguje:</span> Vše</p>\n"
                                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Info k fungování:</span></p>\n"
                                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nahoru doplňte údaje.</p>\n"
                                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Je třeba mít v počítači stáhnutý a nainstalovaný prohlížeč google chrome a mít k němu stažení webdriver, který je určený k jeho verzi.</p>\n"
                                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
                                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Info o aplikace:</span></p>\n"
                                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Autor nenese žádnou zodpovědnost za to jak budete aplikaci používat, jedná se jen o projekt for fun. </p>\n"
                                                               "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dále rovnou uvádím, že používání jakýchkoliv automatických scriptu je dle pravidel zakázáno.</p></body></html>",
                                                               None, -1))
        self.create_save.setText(
            QtWidgets.QApplication.translate("Tabulky", "Vytvořit save LogInu, hesla a driveru", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.basic),
                                  QtWidgets.QApplication.translate("Tabulky", "Basic", None, -1))
        self.trh_whathap.setHtml(QtWidgets.QApplication.translate("Tabulky",
                                                                  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                  "p, li { white-space: pre-wrap; }\n"
                                                                  "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                                                  "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Waiting...</p></body></html>",
                                                                  None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("Tabulky", "What happens", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Tabulky", "Získání jen informací", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Tabulky", "Tabulka s průměrnou cenou v čase", None, -1))
        self.trhinf_button_tabulka.setText(
            QtWidgets.QApplication.translate("Tabulky", "Získání cen do tabulky", None, -1))
        self.trhinf_button_zboziallview.setText(
            QtWidgets.QApplication.translate("Tabulky", "Ukázání celkové tabulky/grafu", None, -1))
        self.trhinf_button_zbozi72.setText(
            QtWidgets.QApplication.translate("Tabulky", "Podrobný graf/tabulka za 72h", None, -1))
        __sortingEnabled = self.trhinf_tabulka.isSortingEnabled()
        self.trhinf_tabulka.setSortingEnabled(False)
        self.trhinf_tabulka.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Čas", None, -1))
        self.trhinf_tabulka.item(0, 1).setText(QtWidgets.QApplication.translate("Tabulky", "Now", None, -1))
        self.trhinf_tabulka.item(0, 2).setText(QtWidgets.QApplication.translate("Tabulky", "1h", None, -1))
        self.trhinf_tabulka.item(0, 3).setText(QtWidgets.QApplication.translate("Tabulky", "12h", None, -1))
        self.trhinf_tabulka.item(0, 4).setText(QtWidgets.QApplication.translate("Tabulky", "24h", None, -1))
        self.trhinf_tabulka.item(0, 5).setText(QtWidgets.QApplication.translate("Tabulky", "36h", None, -1))
        self.trhinf_tabulka.item(0, 6).setText(QtWidgets.QApplication.translate("Tabulky", "48h", None, -1))
        self.trhinf_tabulka.item(0, 7).setText(QtWidgets.QApplication.translate("Tabulky", "60h", None, -1))
        self.trhinf_tabulka.item(0, 8).setText(QtWidgets.QApplication.translate("Tabulky", "72h", None, -1))
        self.trhinf_tabulka.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Jídlo", None, -1))
        self.trhinf_tabulka.item(2, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Energie", None, -1))
        self.trhinf_tabulka.item(3, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Vojáci", None, -1))
        self.trhinf_tabulka.item(4, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Tanky", None, -1))
        self.trhinf_tabulka.item(5, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Stíhačky", None, -1))
        self.trhinf_tabulka.item(6, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Bunkry", None, -1))
        self.trhinf_tabulka.item(7, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Mechy", None, -1))
        self.trhinf_tabulka.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.zbozi),
                                QtWidgets.QApplication.translate("Tabulky", "Zboží", None, -1))
        __sortingEnabled = self.trhinf_tabulka_2.isSortingEnabled()
        self.trhinf_tabulka_2.setSortingEnabled(False)
        self.trhinf_tabulka_2.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Čas", None, -1))
        self.trhinf_tabulka_2.item(0, 1).setText(QtWidgets.QApplication.translate("Tabulky", "Now", None, -1))
        self.trhinf_tabulka_2.item(0, 2).setText(QtWidgets.QApplication.translate("Tabulky", "1h", None, -1))
        self.trhinf_tabulka_2.item(0, 3).setText(QtWidgets.QApplication.translate("Tabulky", "12h", None, -1))
        self.trhinf_tabulka_2.item(0, 4).setText(QtWidgets.QApplication.translate("Tabulky", "24h", None, -1))
        self.trhinf_tabulka_2.item(0, 5).setText(QtWidgets.QApplication.translate("Tabulky", "36h", None, -1))
        self.trhinf_tabulka_2.item(0, 6).setText(QtWidgets.QApplication.translate("Tabulky", "48h", None, -1))
        self.trhinf_tabulka_2.item(0, 7).setText(QtWidgets.QApplication.translate("Tabulky", "60h", None, -1))
        self.trhinf_tabulka_2.item(0, 8).setText(QtWidgets.QApplication.translate("Tabulky", "72h", None, -1))
        self.trhinf_tabulka_2.item(1, 0).setText(
            QtWidgets.QApplication.translate("Tabulky", "Rychlost stavby", None, -1))
        self.trhinf_tabulka_2.item(2, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Obchod", None, -1))
        self.trhinf_tabulka_2.item(3, 0).setText(
            QtWidgets.QApplication.translate("Tabulky", "Hustota zalidnění", None, -1))
        self.trhinf_tabulka_2.item(4, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Zemědělství", None, -1))
        self.trhinf_tabulka_2.item(5, 0).setText(
            QtWidgets.QApplication.translate("Tabulky", "Automatizace továren", None, -1))
        self.trhinf_tabulka_2.item(6, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Energetika", None, -1))
        self.trhinf_tabulka_2.item(7, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Síla zbraní", None, -1))
        self.trhinf_tabulka_2.item(8, 0).setText(
            QtWidgets.QApplication.translate("Tabulky", "Cena na dom.trhu", None, -1))
        self.trhinf_tabulka_2.item(9, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Vývoj raket", None, -1))
        self.trhinf_tabulka_2.item(10, 0).setText(
            QtWidgets.QApplication.translate("Tabulky", "Protiraketová obrana", None, -1))
        self.trhinf_tabulka_2.item(11, 0).setText(
            QtWidgets.QApplication.translate("Tabulky", "Síla rozvědky", None, -1))
        self.trhinf_tabulka_2.item(12, 0).setText(
            QtWidgets.QApplication.translate("Tabulky", "Výzkum vesmíru", None, -1))
        self.trhinf_tabulka_2.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.technologie),
                                QtWidgets.QApplication.translate("Tabulky", "Technologie", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za poslední hodinu", None, -1))
        __sortingEnabled = self.thrdetail_tabulka1h.isSortingEnabled()
        self.thrdetail_tabulka1h.setSortingEnabled(False)
        self.thrdetail_tabulka1h.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.thrdetail_tabulka1h.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.thrdetail_tabulka1h.setSortingEnabled(__sortingEnabled)
        self.label_40.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za celou dobu", None, -1))
        self.trhdetail_graf1h.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_all.isSortingEnabled()
        self.trhdetail_all.setSortingEnabled(False)
        self.trhdetail_all.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_all.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_all.setSortingEnabled(__sortingEnabled)
        self.label_25.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za posledních 12h", None, -1))
        self.trhdetail_graf12.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_12h.isSortingEnabled()
        self.trhdetail_12h.setSortingEnabled(False)
        self.trhdetail_12h.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_12h.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_12h.setSortingEnabled(__sortingEnabled)
        self.trhdetail_button_all.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.jidlo_detail),
                                QtWidgets.QApplication.translate("Tabulky", "Jídlo", None, -1))
        __sortingEnabled = self.thrdetail_tabulka1h_2.isSortingEnabled()
        self.thrdetail_tabulka1h_2.setSortingEnabled(False)
        self.thrdetail_tabulka1h_2.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.thrdetail_tabulka1h_2.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.thrdetail_tabulka1h_2.setSortingEnabled(__sortingEnabled)
        self.label_41.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za poslední hodinu", None, -1))
        self.trhdetail_graf1h_2.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_all_2.isSortingEnabled()
        self.trhdetail_all_2.setSortingEnabled(False)
        self.trhdetail_all_2.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_all_2.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_all_2.setSortingEnabled(__sortingEnabled)
        self.trhdetail_graf12_2.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za celou dobu", None, -1))
        self.trhdetail_button_all_2.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za posledních 12h", None, -1))
        __sortingEnabled = self.trhdetail_12h_2.isSortingEnabled()
        self.trhdetail_12h_2.setSortingEnabled(False)
        self.trhdetail_12h_2.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_12h_2.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_12h_2.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.ene_detail),
                                QtWidgets.QApplication.translate("Tabulky", "Energie", None, -1))
        __sortingEnabled = self.thrdetail_tabulka1h_3.isSortingEnabled()
        self.thrdetail_tabulka1h_3.setSortingEnabled(False)
        self.thrdetail_tabulka1h_3.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.thrdetail_tabulka1h_3.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.thrdetail_tabulka1h_3.setSortingEnabled(__sortingEnabled)
        self.label_44.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za poslední hodinu", None, -1))
        self.trhdetail_graf1h_3.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_all_3.isSortingEnabled()
        self.trhdetail_all_3.setSortingEnabled(False)
        self.trhdetail_all_3.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_all_3.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_all_3.setSortingEnabled(__sortingEnabled)
        self.trhdetail_graf12_3.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za celou dobu", None, -1))
        self.trhdetail_button_all_3.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za posledních 12h", None, -1))
        __sortingEnabled = self.trhdetail_12h_3.isSortingEnabled()
        self.trhdetail_12h_3.setSortingEnabled(False)
        self.trhdetail_12h_3.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_12h_3.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_12h_3.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.voj_detail),
                                QtWidgets.QApplication.translate("Tabulky", "Vojáci", None, -1))
        __sortingEnabled = self.thrdetail_tabulka1h_4.isSortingEnabled()
        self.thrdetail_tabulka1h_4.setSortingEnabled(False)
        self.thrdetail_tabulka1h_4.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.thrdetail_tabulka1h_4.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.thrdetail_tabulka1h_4.setSortingEnabled(__sortingEnabled)
        self.label_47.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za poslední hodinu", None, -1))
        self.trhdetail_graf1h_4.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_all_4.isSortingEnabled()
        self.trhdetail_all_4.setSortingEnabled(False)
        self.trhdetail_all_4.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_all_4.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_all_4.setSortingEnabled(__sortingEnabled)
        self.trhdetail_graf12_4.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za celou dobu", None, -1))
        self.trhdetail_button_all_4.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za posledních 12h", None, -1))
        __sortingEnabled = self.trhdetail_12h_4.isSortingEnabled()
        self.trhdetail_12h_4.setSortingEnabled(False)
        self.trhdetail_12h_4.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_12h_4.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_12h_4.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.tanky_detail),
                                QtWidgets.QApplication.translate("Tabulky", "Tanky", None, -1))
        __sortingEnabled = self.thrdetail_tabulka1h_5.isSortingEnabled()
        self.thrdetail_tabulka1h_5.setSortingEnabled(False)
        self.thrdetail_tabulka1h_5.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.thrdetail_tabulka1h_5.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.thrdetail_tabulka1h_5.setSortingEnabled(__sortingEnabled)
        self.label_50.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za poslední hodinu", None, -1))
        self.trhdetail_graf1h_5.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_all_5.isSortingEnabled()
        self.trhdetail_all_5.setSortingEnabled(False)
        self.trhdetail_all_5.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_all_5.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_all_5.setSortingEnabled(__sortingEnabled)
        self.trhdetail_graf12_5.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za celou dobu", None, -1))
        self.trhdetail_button_all_5.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za posledních 12h", None, -1))
        __sortingEnabled = self.trhdetail_12h_5.isSortingEnabled()
        self.trhdetail_12h_5.setSortingEnabled(False)
        self.trhdetail_12h_5.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_12h_5.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_12h_5.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.stihy_detail),
                                QtWidgets.QApplication.translate("Tabulky", "Stíhačky", None, -1))
        __sortingEnabled = self.thrdetail_tabulka1h_6.isSortingEnabled()
        self.thrdetail_tabulka1h_6.setSortingEnabled(False)
        self.thrdetail_tabulka1h_6.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.thrdetail_tabulka1h_6.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.thrdetail_tabulka1h_6.setSortingEnabled(__sortingEnabled)
        self.label_53.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za poslední hodinu", None, -1))
        self.trhdetail_graf1h_6.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_all_6.isSortingEnabled()
        self.trhdetail_all_6.setSortingEnabled(False)
        self.trhdetail_all_6.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_all_6.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_all_6.setSortingEnabled(__sortingEnabled)
        self.trhdetail_graf12_6.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_54.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za celou dobu", None, -1))
        self.trhdetail_button_all_6.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_55.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za posledních 12h", None, -1))
        __sortingEnabled = self.trhdetail_12h_6.isSortingEnabled()
        self.trhdetail_12h_6.setSortingEnabled(False)
        self.trhdetail_12h_6.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_12h_6.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_12h_6.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.bunkry_detail),
                                QtWidgets.QApplication.translate("Tabulky", "Bunkry", None, -1))
        __sortingEnabled = self.thrdetail_tabulka1h_7.isSortingEnabled()
        self.thrdetail_tabulka1h_7.setSortingEnabled(False)
        self.thrdetail_tabulka1h_7.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.thrdetail_tabulka1h_7.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.thrdetail_tabulka1h_7.setSortingEnabled(__sortingEnabled)
        self.label_56.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za poslední hodinu", None, -1))
        self.trhdetail_graf1h_7.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        __sortingEnabled = self.trhdetail_all_7.isSortingEnabled()
        self.trhdetail_all_7.setSortingEnabled(False)
        self.trhdetail_all_7.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_all_7.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_all_7.setSortingEnabled(__sortingEnabled)
        self.trhdetail_graf12_7.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za celou dobu", None, -1))
        self.trhdetail_button_all_7.setText(QtWidgets.QApplication.translate("Tabulky", "Graf", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("Tabulky", "Cena za posledních 12h", None, -1))
        __sortingEnabled = self.trhdetail_12h_7.isSortingEnabled()
        self.trhdetail_12h_7.setSortingEnabled(False)
        self.trhdetail_12h_7.item(0, 0).setText(QtWidgets.QApplication.translate("Tabulky", "Cena", None, -1))
        self.trhdetail_12h_7.item(1, 0).setText(QtWidgets.QApplication.translate("Tabulky", "čas", None, -1))
        self.trhdetail_12h_7.setSortingEnabled(__sortingEnabled)
        self.trh_trh.setTabText(self.trh_trh.indexOf(self.mechy_detail),
                                QtWidgets.QApplication.translate("Tabulky", "Mechy", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Tabulky", "Zboží", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Tabulky", "Technologie", None, -1))
        self.thrinf_button_tech72.setText(
            QtWidgets.QApplication.translate("Tabulky", "Podrobný graf/tabulka za 72h", None, -1))
        self.trhinf_button_techallview.setText(
            QtWidgets.QApplication.translate("Tabulky", "Ukázání celkové tabulky/grafu", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trh),
                                  QtWidgets.QApplication.translate("Tabulky", "Trh", None, -1))
        self.domtrh_button_startpreprodej.setText(QtWidgets.QApplication.translate("Tabulky", "Start", None, -1))
        self.trh_checkBox_bunkry.setText(QtWidgets.QApplication.translate("Tabulky", "Bunkry", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Tabulky", "Navýšit prod. cenu:", None, -1))
        self.trh_checkBox_jidlo.setText(QtWidgets.QApplication.translate("Tabulky", "Jídlo", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Tabulky", "Co chci přeprodávat", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("Tabulky", "Min. částka výdělku:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Tabulky", "Přeprodej světového trhu", None, -1))
        self.svtrh_button_startprepodej.setText(QtWidgets.QApplication.translate("Tabulky", "Start", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("Tabulky", "Přeprodej domacího trhu", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Tabulky", "Kolik chci utratit:", None, -1))
        self.trh_checkBox_energie.setText(QtWidgets.QApplication.translate("Tabulky", "Energie", None, -1))
        self.trh_checkBox_tanky.setText(QtWidgets.QApplication.translate("Tabulky", "Tanky", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Tabulky", "Navýšit prod. cenu:", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("Tabulky", "Přeprodej", None, -1))
        self.trh_checkBox_stihacky.setText(QtWidgets.QApplication.translate("Tabulky", "Stíhačky", None, -1))
        self.trh_checkBox_vojaci.setText(QtWidgets.QApplication.translate("Tabulky", "Vojáci", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Tabulky", "Min. částka výdělku:", None, -1))
        self.trh_checkBox_all.setText(QtWidgets.QApplication.translate("Tabulky", "Vše", None, -1))
        self.trh_checkBox_mechy.setText(QtWidgets.QApplication.translate("Tabulky", "Mechy", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Tabulky", "Kolik chci utrati:", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("Tabulky", "What happens", None, -1))
        self.trhpreprodej_whathap.setHtml(QtWidgets.QApplication.translate("Tabulky",
                                                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                           "p, li { white-space: pre-wrap; }\n"
                                                                           "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Waiting...</p></body></html>",
                                                                           None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("Tabulky", "Co se vyplatí", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trh_preprodej),
                                  QtWidgets.QApplication.translate("Tabulky", "Trh přeprodej", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("Tabulky", "Celkový počet pokusů:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Tabulky", "Počet neúspěšných pokusů:", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("Tabulky", "Počet prohledávaných zemí:", None, -1))
        self.rozvedka_button_start.setText(QtWidgets.QApplication.translate("Tabulky", "Start", None, -1))
        self.rozv_rovnouzemivykrast_2.setText(
            QtWidgets.QApplication.translate("Tabulky", "Chci zemi rovnou zkusit vykrást:", None, -1))
        self.rozv_vyhledatzeme_2.setText(
            QtWidgets.QApplication.translate("Tabulky", "Vyhledat země na wgtabs.info:", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Tabulky", "Rozvědka", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Tabulky", "TOP10", None, -1))
        self.rozvedka_whathap.setHtml(QtWidgets.QApplication.translate("Tabulky",
                                                                       "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                       "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                       "p, li { white-space: pre-wrap; }\n"
                                                                       "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                                                       "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Waiting...</p></body></html>",
                                                                       None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("Tabulky", "What happens", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Tabulky", "Nastaveni", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rozvedka),
                                  QtWidgets.QApplication.translate("Tabulky", "Rozvědka", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Tabulky", "Někdy v  budoucnu", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("Tabulky", "What happens", None, -1))
        self.textEdit_6.setHtml(QtWidgets.QApplication.translate("Tabulky",
                                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                 "p, li { white-space: pre-wrap; }\n"
                                                                 "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Waiting...</p></body></html>",
                                                                 None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.war),
                                  QtWidgets.QApplication.translate("Tabulky", "Válčení", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Tabulky", "Někdy možná v budoucnu", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("Tabulky", "What happens", None, -1))
        self.textEdit_7.setHtml(QtWidgets.QApplication.translate("Tabulky",
                                                                 "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                 "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                 "p, li { white-space: pre-wrap; }\n"
                                                                 "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                                                 "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Waiting...</p></body></html>",
                                                                 None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.technology),
                                  QtWidgets.QApplication.translate("Tabulky", "Technologie", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("Tabulky", "What happens", None, -1))
        self.archiv_whathap.setHtml(QtWidgets.QApplication.translate("Tabulky",
                                                                     "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                                     "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                                     "p, li { white-space: pre-wrap; }\n"
                                                                     "</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
                                                                     "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Waiting...</p></body></html>",
                                                                     None, -1))
        self.archiv_button_save_archiv.setText(QtWidgets.QApplication.translate("Tabulky", "Start", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("Tabulky", "Archiv", None, -1))
        self.archiv_toexcel_2.setText(
            QtWidgets.QApplication.translate("Tabulky", "Uložit celý archiv do excelu:", None, -1))
        self.archiv_best_2.setText(
            QtWidgets.QApplication.translate("Tabulky", "Vypsat to nejlepší z mého archivu:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Tabulky", "Uložení cen trhu do excelu", None, -1))
        self.archiv_button_saveexcel_trh.setText(QtWidgets.QApplication.translate("Tabulky", "Start", None, -1))
        self.label_12.setText(
            QtWidgets.QApplication.translate("Tabulky", "Uloží všechny ceny které se zatím objevili na trhu do excelu",
                                             None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.archiv),
                                  QtWidgets.QApplication.translate("Tabulky", "Archivace dat", None, -1))

    def changetext(self, Tabulky):
        self.archiv_whathap.append('Ahoj')